---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yihuaiyuan.
--- DateTime: 2018/9/11 下午4:52
--- 插入排序

function insertion_sort(array, len)
    for i=2, len do
        if (array[i-1] > array[i]) then
            tmp = array[i]
            for j=i-1,1,-1 do
                if(array[j] > tmp) then
                    array[j+1] = array[j]
                    array[j] = tmp
                    break
                end
            end
        end
    end
    return array
end
