---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yihuaiyuan.
--- DateTime: 2018/9/12 下午3:26
---

function selection_sort(arr, length)
    for i=1, length do
        for j=i,length do
            if (arr[i] > arr[j]) then
                arr[i], arr[j] = arr[j], arr[i]
            end
        end
    end
    return arr
end

