---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yihuaiyuan.
--- DateTime: 2018/9/11 下午4:46
---
--- 冒泡排序

function bubble_sort(array, len)
    for i=1, len do
        for j=1, len-i do
            if(array[j] > array[j+1]) then
                array[j], array[j+1] = array[j+1], array[j]
            end
        end
    end
    return array
end
