---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yihuaiyuan.
--- DateTime: 2018/9/11 下午5:07
--- 快速排序

function myprint(arr)
    for ley,val in pairs(ret) do
        print(val)
    end
end

function quick_sort(arr)
    length = #arr
    if length <= 1 then
        return arr
    end

    mid_key = 1
    mid_val = arr[mid_key]
    left, mid, right = {}, {}, {}

    for i=1,length do
        if mid_val > arr[i]
        then
            table.insert(left,arr[i])
        elseif(mid_val == arr[i])
        then
            table.insert(mid, arr[i])
        else
            table.insert(right,arr[i])
        end
    end

    return array_merge(quick_sort(left), {mid_val}, quick_sort(right))
end

function array_merge(...)
    ret = {}
    for _,arr in pairs({...}) do
        for i=1, #arr do
            table.insert(ret,arr[i])
        end
    end
    return ret
end

arr1 = {7,2,6,0,91,2,4}
arr2 = {6,5,8}
arr3 = {0,91,2,4}

